### ISSUE TITLE
No module named parse

### ISSUE THREAD

**Issue by bavan999** [simonschellaert/spotify2am#15]
i get an error trying to run "retrieve-identifiers.py"

~/Desktop/spotify2am-master/retrieve-identifiers.py:3: ImportError: No module named parse

I run the script in TextWrangler

**Comment by nathanberg** [comment]
I suspect that TextWrangler is using Python 2.7
Try opening a terminal and manually running python 3 with "python3 file/path/here/retrieve-identifiers.py"

**Comment by bavan999** [comment]
Some progress with retrieve.identifiers TextWrangler was an absolute issue.

File "/Users/bavan/Desktop/spotify2am-master/retrieve-identifiers.py", line 38, in <module>
    with open('spotify.csv', encoding='utf-8') as playlist_file:
FileNotFoundError: [Errno 2] No such file or directory: 'spotify.csv'

Richards-iMac:~ bavan$ PYTHONIOENCODING=utf-8 python3 /Users/bavan/Desktop/spotify2am-master/retrieve-identifiers.py
Traceback (most recent call last):
  File "/Users/bavan/Desktop/spotify2am-master/retrieve-identifiers.py", line 38, in <module>
    with open('spotify.csv', encoding='utf-8') as playlist_file:
FileNotFoundError: [Errno 2] No such file or directory: 'spotify.csv'

**Comment by bavan999** [comment]
I think i solved the problem. I am now running the script in IDLE and it seems to work properly.
Hopefully the itunes.csv will be created just fine, even though i can't se the file right now.

**Comment by bavan999** [comment]
Something went really really wrong.... The script imported same song 1.4 million times... 
My itunes library is so f**d.... Think i will go back to an old backup to restore.
