### ISSUE TITLE
invalid continuation byte

### ISSUE THREAD

**Issue by ashleyknutsen** [simonschellaert/spotify2am#6]
Maxs-MBP:spotify2am mknutsen$ PYTHONIOENCODING=utf-8 python3 retrieve-identifiers.py
Traceback (most recent call last):
  File "retrieve-identifiers.py", line 40, in <module>
    next(playlist_reader)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 8: invalid continuation byte

**Comment by lord-enzo** [comment]
same here
